### ISSUE TITLE
Fat fs driver

### ISSUE THREAD

**Issue by Prathik4** [gonzoua/u-boot-pi#11]
Hello,
You have done a great job.
I'm newbie to bare metal programming. I'm working on a academic project were I'm using freeRTOS to run 2 tasks on the raspberry pi board and while doing that I want to store some data in USB storage. So iIwas wondering if the fat fs driver provided by you can be used along side freeRTOS to write to fat filesystem?
Thank you in advance.. 👍

**Comment by gonzoua** [comment]
I only added RPi support to U-Boot. And it's mostly merged to mainline u-boot, so it's better to use latest release: http://git.denx.de/?p=u-boot.git;a=summary

FAT driver there is written by other people and I think it's GPL licensed. I do not know freeRTOS licensing position so can't advice here, you'd better ask someone in freeRTOS community.

**Comment by Prathik4** [comment]
Thanks for replying back.
